<?php
namespace CJDennis\Charset;

class CharsetTestCharacters {
  const ASCII_QUOTATION_MARK = '"';
  const ASCII_APOSTROPHE = "'";
  const ASCII_QUESTION_MARK = '?';

  const CP1252_LEFT_SINGLE_QUOTATION_MARK = "\x91";
  const CP1252_RIGHT_SINGLE_QUOTATION_MARK = "\x92";
  const CP1252_LEFT_DOUBLE_QUOTATION_MARK = "\x93";
  const CP1252_RIGHT_DOUBLE_QUOTATION_MARK = "\x94";
  const CP1252_CURRENCY_SIGN = "\xA4";

  const UTF8_CURRENCY_SIGN = "\xC2\xA4";
  const UTF8_LEFT_SINGLE_QUOTATION_MARK = "\xE2\x80\x98";
  const UTF8_RIGHT_SINGLE_QUOTATION_MARK = "\xE2\x80\x99";
  const UTF8_LEFT_DOUBLE_QUOTATION_MARK = "\xE2\x80\x9C";
  const UTF8_RIGHT_DOUBLE_QUOTATION_MARK = "\xE2\x80\x9D";
}
