<?php
namespace CJDennis\Charset;

class CharsetTestCharacters {
  const ASCII_QUOTATION_MARK = '"';
  const ASCII_APOSTROPHE = "'";
  const ASCII_ASTERISK = '*';
  const ASCII_QUESTION_MARK = '?';

  const CP1252_LEFT_SINGLE_QUOTATION_MARK = "\x91";
  const CP1252_RIGHT_SINGLE_QUOTATION_MARK = "\x92";
  const CP1252_LEFT_DOUBLE_QUOTATION_MARK = "\x93";
  const CP1252_RIGHT_DOUBLE_QUOTATION_MARK = "\x94";
  const CP1252_CURRENCY_SIGN = "\xA4";

  const UTF8_CURRENCY_SIGN = "\xC2\xA4";
  const UTF8_LEFT_SINGLE_QUOTATION_MARK = "\xE2\x80\x98";
  const UTF8_RIGHT_SINGLE_QUOTATION_MARK = "\xE2\x80\x99";
  const UTF8_LEFT_DOUBLE_QUOTATION_MARK = "\xE2\x80\x9C";
  const UTF8_RIGHT_DOUBLE_QUOTATION_MARK = "\xE2\x80\x9D";

  const UTF8_QUESTION_MARK = "\x3F";
  const UTF8_INVERTED_QUESTION_MARK = "\xC2\xBF";
  const UTF8_GREEK_QUESTION_MARK = "\xCD\xBE";
  const UTF8_ARMENIAN_QUESTION_MARK = "\xD5\x9E";
  const UTF8_ARABIC_QUESTION_MARK = "\xD8\x9F";
  const UTF8_ETHIOPIC_QUESTION_MARK = "\xE1\x8D\xA7";
  const UTF8_LIMBU_QUESTION_MARK = "\xE1\xA5\x85";
  const UTF8_DOUBLE_QUESTION_MARK = "\xE2\x81\x87";
  const UTF8_QUESTION_EXCLAMATION_MARK = "\xE2\x81\x88";
  const UTF8_EXCLAMATION_QUESTION_MARK = "\xE2\x81\x89";
  const UTF8_QUESTIONED_EQUAL_TO = "\xE2\x89\x9F";
  const UTF8_APL_FUNCTIONAL_SYMBOL_QUAD_QUESTION = "\xE2\x8D\xB0";
  const UTF8_BLACK_QUESTION_MARK_ORNAMENT = "\xE2\x9D\x93";
  const UTF8_WHITE_QUESTION_MARK_ORNAMENT = "\xE2\x9D\x94";
  const UTF8_LESS_THAN_WITH_QUESTION_MARK_ABOVE = "\xE2\xA9\xBB";
  const UTF8_GREATER_THAN_WITH_QUESTION_MARK_ABOVE = "\xE2\xA9\xBC";
  const UTF8_COPTIC_OLD_NUBIAN_DIRECT_QUESTION_MARK = "\xE2\xB3\xBA";
  const UTF8_COPTIC_OLD_NUBIAN_INDIRECT_QUESTION_MARK = "\xE2\xB3\xBB";
  const UTF8_REVERSED_QUESTION_MARK = "\xE2\xB8\xAE";
  const UTF8_CIRCLED_IDEOGRAPH_QUESTION = "\xE3\x89\x84";
  const UTF8_VAI_QUESTION_MARK = "\xEA\x98\x8F";
  const UTF8_BAMUM_QUESTION_MARK = "\xEA\x9B\xB7";
  const UTF8_PRESENTATION_FORM_FOR_VERTICAL_QUESTION_MARK = "\xEF\xB8\x96";
  const UTF8_SMALL_QUESTION_MARK = "\xEF\xB9\x96";
  const UTF8_FULLWIDTH_QUESTION_MARK = "\xEF\xBC\x9F";
  const UTF8_CHAKMA_QUESTION_MARK = "\xF0\x91\x85\x83";
  const UTF8_ADLAM_INITIAL_QUESTION_MARK = "\xF0\x9E\xA5\x9F";
  const UTF8_TAG_QUESTION_MARK = "\xF3\xA0\x80\xBF";
}
